-- TaskTrace — RLS policies, authorization helpers and security-definer RPCs.
-- Migration 0002. Requires 20260901000000_initial_schema.sql to be applied.
--
-- Design:
--   * Authorization helpers live in schema `private` (not exposed via PostgREST,
--     which only serves `public`/configured schemas). All helpers are
--     SECURITY DEFINER with a fixed search_path so that:
--       - RLS policy predicates cannot recurse into RLS-protected tables;
--       - policy subqueries cannot be tampered with via search_path;
--       - callers cannot alter their behaviour.
--   * Every sensitive write operation is a SECURITY DEFINER RPC in `public`
--     that performs its own authorization. `is_completed` on task_items can
--     ONLY be changed through set_task_item_state() because direct
--     INSERT/UPDATE on task_items is revoked from anon/authenticated.
--   * item_actions and audit_log are SELECT-only for authenticated; INSERTs
--     happen exclusively inside server-side RPCs / triggers.
--   * All timestamps are timestamptz generated by PostgreSQL (now());
--     user identity comes from auth.uid() — never from client input.
--
-- Supabase compatibility: if the standard Supabase roles (anon, authenticated,
-- service_role) do not exist (plain PostgreSQL), they are created here.

create extension if not exists pgcrypto;

-- -----------------------------------------------------------------------------
-- Supabase roles (no-op on hosted Supabase)
-- -----------------------------------------------------------------------------

do $$
begin
    if not exists (select 1 from pg_roles where rolname = 'anon') then
        create role anon nologin noinherit;
    end if;
    if not exists (select 1 from pg_roles where rolname = 'authenticated') then
        create role authenticated nologin noinherit;
    end if;
    if not exists (select 1 from pg_roles where rolname = 'service_role') then
        create role service_role nologin noinherit bypassrls;
    end if;
end
$$;

-- -----------------------------------------------------------------------------
-- Private schema for internal authorization helpers
-- -----------------------------------------------------------------------------

create schema if not exists private;

revoke all on schema private from public;

-- -----------------------------------------------------------------------------
-- Authorization helper functions (SECURITY DEFINER, fixed search_path)
-- -----------------------------------------------------------------------------

-- Caller must be authenticated; returns auth.uid() or raises.
create function private.require_auth()
returns uuid
language plpgsql
stable
security definer
set search_path = private, public
as $$
declare
    v_user uuid := auth.uid();
begin
    if v_user is null then
        raise exception 'authentication required'
            using errcode = 'insufficient_privilege'; -- 42501
    end if;
    return v_user;
end
$$;

-- Role of a user in a project; null when the user is not a project member.
create function private.project_role_of(p_project_id uuid, p_user_id uuid default auth.uid())
returns public.project_role
language sql
stable
security definer
set search_path = private, public
as $$
    select pm.role
    from public.project_members pm
    where pm.project_id = p_project_id
      and pm.user_id = p_user_id;
$$;

create function private.is_project_member(p_project_id uuid, p_user_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = private, public
as $$
    select private.project_role_of(p_project_id, p_user_id) is not null;
$$;

create function private.is_project_owner(p_project_id uuid, p_user_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = private, public
as $$
    select private.project_role_of(p_project_id, p_user_id) = 'owner';
$$;

-- Owner or admin.
create function private.is_project_admin(p_project_id uuid, p_user_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = private, public
as $$
    select private.project_role_of(p_project_id, p_user_id) in ('owner', 'admin');
$$;

create function private.project_is_active(p_project_id uuid)
returns boolean
language sql
stable
security definer
set search_path = private, public
as $$
    select exists (
        select 1 from public.projects
        where id = p_project_id and status = 'active'
    );
$$;

create function private.task_project_id(p_task_id uuid)
returns uuid
language sql
stable
security definer
set search_path = private, public
as $$
    select t.project_id from public.tasks t where t.id = p_task_id;
$$;

-- Access to a concrete task = project membership AND approved task_members row.
create function private.has_task_access(p_task_id uuid, p_user_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = private, public
as $$
    select exists (
        select 1
        from public.tasks t
        join public.project_members pm
             on pm.project_id = t.project_id and pm.user_id = p_user_id
        join public.task_members tm
             on tm.task_id = t.id and tm.user_id = p_user_id
        where t.id = p_task_id
    );
$$;

-- Can see project-level metadata (project_members, audit_log) of the task's project.
create function private.has_project_view_of_task(p_task_id uuid, p_user_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = private, public
as $$
    select private.is_project_member(private.task_project_id(p_task_id), p_user_id);
$$;

-- May modify task content: task access AND project role != viewer.
create function private.can_edit_task(p_task_id uuid, p_user_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = private, public
as $$
    select private.has_task_access(p_task_id, p_user_id)
       and private.project_role_of(private.task_project_id(p_task_id), p_user_id) <> 'viewer';
$$;

-- Task content is mutable only while the task and its project are active.
create function private.task_is_editable(p_task_id uuid)
returns boolean
language sql
stable
security definer
set search_path = private, public
as $$
    select exists (
        select 1
        from public.tasks t
        where t.id = p_task_id
          and t.status <> 'archived'
          and exists (select 1 from public.projects p
                      where p.id = t.project_id and p.status = 'active')
    );
$$;

-- -----------------------------------------------------------------------------
-- Profile provisioning (auth.users -> public.profiles)
-- -----------------------------------------------------------------------------
-- NOTE: the provisioning trigger is intentionally NOT created in this migration.
-- The baseline smoke test (initial_schema_smoke_test.sql) provisions profiles
-- explicitly; enabling the trigger now would break it. Activate it at the
-- auth-integration stage with:
--   create trigger on_auth_user_created
--   after insert on auth.users
--   for each row execute function private.handle_new_user();

create function private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = private, public
as $$
begin
    insert into public.profiles (id, display_name)
    values (
        new.id,
        coalesce(
            new.raw_user_meta_data ->> 'display_name',
            new.raw_user_meta_data ->> 'name',
            split_part(coalesce(new.email, 'user'), '@', 1)
        )
    )
    on conflict (id) do nothing;
    return new;
end
$$;

-- -----------------------------------------------------------------------------
-- Server-side audit for direct (RLS-permitted) updates of projects/tasks.
--
-- Runs as SECURITY DEFINER so that the audit_log INSERT succeeds even though
-- authenticated has no INSERT privilege on audit_log. user_id = auth.uid();
-- skipped when there is no authenticated user (system/service context), which
-- also keeps baseline smoke tests deterministic.
-- -----------------------------------------------------------------------------

create function private.audit_entity_update()
returns trigger
language plpgsql
security definer
set search_path = private, public
as $$
declare
    v_old jsonb;
    v_new jsonb;
    v_action public.audit_action;
    v_project_id uuid;
    v_entity text;
begin
    if auth.uid() is null then
        return null; -- system/service context: no user-attributable audit
    end if;

    if tg_table_name = 'projects' then
        v_entity := 'project';
        v_project_id := old.id;
    else
        v_entity := 'task';
        v_project_id := old.project_id;
    end if;

    v_action := case
        when old.status <> 'archived' and new.status = 'archived' then 'archived'::public.audit_action
        else 'updated'::public.audit_action
    end;

    select jsonb_object_agg(o.key, o.value),
           jsonb_object_agg(n.key, n.value)
      into v_old, v_new
    from jsonb_each(to_jsonb(old)) o
    join jsonb_each(to_jsonb(new)) n using (key)
    where o.value is distinct from n.value;

    insert into public.audit_log
        (project_id, user_id, action, entity_type, entity_id, old_data, new_data)
    values
        (v_project_id, auth.uid(), v_action, v_entity, old.id, v_old, v_new);

    return null;
end
$$;

create trigger trg_projects_audit
after update on public.projects
for each row
execute function private.audit_entity_update();

create trigger trg_tasks_audit
after update on public.tasks
for each row
execute function private.audit_entity_update();

-- -----------------------------------------------------------------------------
-- Row Level Security policies
-- -----------------------------------------------------------------------------
-- All policies target `authenticated`. anon has no table privileges at all.
-- Row writes for project_members / task_members / task_assignees / task_items /
-- item_actions / audit_log go exclusively through SECURITY DEFINER RPCs.

-- profiles --------------------------------------------------------------------

create policy profiles_select_all
on public.profiles for select
to authenticated
using (true);

create policy profiles_update_self
on public.profiles for update
to authenticated
using (id = auth.uid())
with check (id = auth.uid());

-- projects --------------------------------------------------------------------

create policy projects_select_member
on public.projects for select
to authenticated
using (private.is_project_member(id));

create policy projects_update_admin
on public.projects for update
to authenticated
using (private.is_project_admin(id) and status = 'active')
with check (private.is_project_admin(id) and status <> 'archived');
-- (archiving itself goes through archive_project(); direct archiving by the
--  client is rejected by the WITH CHECK clause above.)

-- project_members -------------------------------------------------------------

create policy project_members_select_project_member
on public.project_members for select
to authenticated
using (private.is_project_member(project_id));

-- tasks -----------------------------------------------------------------------

create policy tasks_select_task_member
on public.tasks for select
to authenticated
using (private.has_task_access(id));

create policy tasks_update_editable
on public.tasks for update
to authenticated
using (private.can_edit_task(id)
       and status <> 'archived'
       and private.project_is_active(project_id))
with check (private.can_edit_task(id) and status <> 'archived');

-- task_members ----------------------------------------------------------------

create policy task_members_select_project_member
on public.task_members for select
to authenticated
using (private.has_project_view_of_task(task_id));

-- task_assignees --------------------------------------------------------------

create policy task_assignees_select_task_member
on public.task_assignees for select
to authenticated
using (private.has_task_access(task_id));

-- task_items ------------------------------------------------------------------

create policy task_items_select_task_member
on public.task_items for select
to authenticated
using (private.has_task_access(task_id));

-- item_actions (read-only; rows are created by server-side RPC) ---------------

create policy item_actions_select_task_member
on public.item_actions for select
to authenticated
using (private.has_task_access(task_id));

-- audit_log (read-only; rows are created by server-side RPC/trigger) ----------

create policy audit_log_select_project_member
on public.audit_log for select
to authenticated
using (private.is_project_member(project_id));

-- -----------------------------------------------------------------------------
-- Grants
-- -----------------------------------------------------------------------------
-- Principle of least privilege: authenticated gets SELECT on all app tables,
-- plus narrow INSERT/UPDATE where RLS policies exist (profiles, projects,
-- tasks). Everything else — including any write to task_items, item_actions
-- and audit_log — only through SECURITY DEFINER RPCs.

do $$
begin
    execute 'grant select on public.profiles, public.projects, public.project_members,
             public.tasks, public.task_members, public.task_assignees,
             public.task_items, public.item_actions, public.audit_log to authenticated';

    execute 'grant insert, update on public.profiles to authenticated';
    execute 'grant update on public.projects, public.tasks to authenticated';

    -- hard guarantees (even if some grant above is ever relaxed)
    execute 'revoke all on all tables in schema public from anon';
    execute 'revoke all on all sequences in schema public from anon';
    execute 'revoke all on all sequences in schema public from authenticated';
    execute 'revoke insert, update, delete, truncate on public.item_actions, public.audit_log from authenticated';
    execute 'revoke insert, update, delete, truncate on public.task_items from authenticated';
    execute 'revoke insert, update, delete, truncate on public.task_members, public.task_assignees, public.project_members from authenticated';

    -- functions: nothing is callable by default
    execute 'revoke all on all functions in schema public from public';

    -- private helpers are callable by authenticated (needed by RLS policies)
    execute 'revoke all on schema private from public, anon';
    execute 'grant usage on schema private to authenticated';
    execute 'grant execute on all functions in schema private to authenticated';
end
$$;

-- -----------------------------------------------------------------------------
-- Public RPCs (SECURITY DEFINER, self-authorizing, fixed search_path)
-- -----------------------------------------------------------------------------
-- Each RPC fully validates authorization server-side. Caller identity always
-- comes from auth.uid(); timestamps from now(). Authorization failures raise
-- SQLSTATE 42501 (insufficient_privilege); business-rule violations raise
-- other explicit errors. Every RPC is a single atomic statement block:
-- any failure rolls back the whole operation.

create function public.create_project(p_name text, p_description text default null)
returns uuid
language plpgsql
security definer
set search_path = private, public
as $$
declare
    v_user uuid := private.require_auth();
    v_id   uuid;
begin
    if p_name is null or length(btrim(p_name)) = 0 then
        raise exception 'project name must not be blank';
    end if;

    insert into public.projects (name, description, created_by)
    values (p_name, p_description, v_user)
    returning id into v_id;

    -- atomic: project exists only together with its owner membership
    insert into public.project_members (project_id, user_id, role)
    values (v_id, v_user, 'owner');

    insert into public.audit_log (project_id, user_id, action, entity_type, entity_id, new_data)
    values (v_id, v_user, 'created', 'project', v_id,
            jsonb_build_object('name', p_name, 'description', p_description));

    return v_id;
end
$$;

create function public.create_task(
    p_project_id uuid,
    p_title text,
    p_description text default null
)
returns uuid
language plpgsql
security definer
set search_path = private, public
as $$
declare
    v_user uuid := private.require_auth();
    v_id   uuid;
begin
    if p_title is null or length(btrim(p_title)) = 0 then
        raise exception 'task title must not be blank';
    end if;

    if not private.is_project_member(p_project_id) then
        raise exception 'not a project member'
            using errcode = 'insufficient_privilege';
    end if;
    if private.project_role_of(p_project_id) = 'viewer' then
        raise exception 'viewers cannot create tasks'
            using errcode = 'insufficient_privilege';
    end if;
    if not private.project_is_active(p_project_id) then
        raise exception 'project is archived';
    end if;

    insert into public.tasks (project_id, title, description, created_by)
    values (p_project_id, p_title, p_description, v_user)
    returning id into v_id;

    -- atomic: creator automatically receives task access
    insert into public.task_members (task_id, user_id, approved_by)
    values (v_id, v_user, v_user);

    insert into public.audit_log (project_id, user_id, action, entity_type, entity_id, new_data)
    values (p_project_id, v_user, 'created', 'task', v_id,
            jsonb_build_object('title', p_title, 'description', p_description));

    return v_id;
end
$$;

create function public.create_task_item(
    p_task_id uuid,
    p_title text,
    p_description text default null,
    p_position numeric default null
)
returns uuid
language plpgsql
security definer
set search_path = private, public
as $$
declare
    v_user uuid := private.require_auth();
    v_id   uuid;
    v_pos  numeric;
begin
    if p_title is null or length(btrim(p_title)) = 0 then
        raise exception 'item title must not be blank';
    end if;

    if not private.has_task_access(p_task_id) then
        raise exception 'no access to task'
            using errcode = 'insufficient_privilege';
    end if;
    if private.project_role_of(private.task_project_id(p_task_id)) = 'viewer' then
        raise exception 'viewers cannot create items'
            using errcode = 'insufficient_privilege';
    end if;
    if not private.task_is_editable(p_task_id) then
        raise exception 'task is archived';
    end if;

    if p_position is null then
        select coalesce(max(position), 0) + 1 into v_pos
        from public.task_items where task_id = p_task_id;
    else
        v_pos := p_position;
    end if;

    insert into public.task_items (task_id, title, description, position)
    values (p_task_id, p_title, p_description, v_pos)
    returning id into v_id;

    insert into public.audit_log (project_id, user_id, action, entity_type, entity_id, new_data)
    select t.project_id, v_user, 'created', 'task_item', v_id,
           jsonb_build_object('title', p_title, 'description', p_description, 'position', v_pos)
    from public.tasks t where t.id = p_task_id;

    return v_id;
end
$$;

-- Edit task item fields (title/description/position). is_completed is NOT
-- editable here — checkbox state changes go exclusively through
-- set_task_item_state(). null = leave the field unchanged.
create function public.update_task_item(
    p_task_item_id uuid,
    p_title text default null,
    p_description text default null,
    p_position numeric default null
)
returns void
language plpgsql
security definer
set search_path = private, public
as $$
declare
    v_user uuid := private.require_auth();
    r      public.task_items%rowtype;
    v_old  jsonb := '{}'::jsonb;
    v_new  jsonb := '{}'::jsonb;
    v_action public.audit_action;
begin
    select * into r
    from public.task_items
    where id = p_task_item_id
    for update;

    if not found
       or not private.has_task_access(r.task_id)
       or private.project_role_of(private.task_project_id(r.task_id)) = 'viewer' then
        raise exception 'no access to task item'
            using errcode = 'insufficient_privilege';
    end if;
    if not private.task_is_editable(r.task_id) or r.is_archived then
        raise exception 'task item is archived';
    end if;

    if p_title is not null and p_title is distinct from r.title then
        if length(btrim(p_title)) = 0 then
            raise exception 'item title must not be blank';
        end if;
        v_old := v_old || jsonb_build_object('title', r.title);
        v_new := v_new || jsonb_build_object('title', p_title);
    end if;
    if p_description is not null and p_description is distinct from r.description then
        v_old := v_old || jsonb_build_object('description', r.description);
        v_new := v_new || jsonb_build_object('description', p_description);
    end if;
    if p_position is not null and p_position is distinct from r.position then
        v_old := v_old || jsonb_build_object('position', r.position);
        v_new := v_new || jsonb_build_object('position', p_position);
    end if;

    if v_new = '{}'::jsonb then
        return; -- nothing changed: no write, no audit
    end if;

    update public.task_items set
        title       = coalesce(p_title, title),
        description = coalesce(p_description, description),
        position    = coalesce(p_position, position)
    where id = r.id;

    v_action := case when v_old ? 'position' then 'reordered' else 'updated' end;

    insert into public.audit_log (project_id, user_id, action, entity_type, entity_id, old_data, new_data)
    select t.project_id, v_user, v_action, 'task_item', r.id, v_old, v_new
    from public.tasks t where t.id = r.task_id;
end
$$;

-- Atomic, idempotent checkbox state change.
-- Contract: row-locked (FOR UPDATE) read -> authorization checks ->
-- no-op when state already matches -> update task_items + insert item_actions
-- + insert audit_log, all in ONE transaction (a plpgsql function runs inside
-- the caller's transaction; any exception rolls back every statement).
create function public.set_task_item_state(
    p_task_item_id uuid,
    p_completed boolean
)
returns boolean
language plpgsql
security definer
set search_path = private, public
as $$
declare
    v_user uuid := private.require_auth();
    r_item public.task_items%rowtype;
    r_task public.tasks%rowtype;
    v_action public.item_action_type;
    v_audit_action public.audit_action;
begin
    select * into r_item
    from public.task_items
    where id = p_task_item_id
    for update;

    if not found or not private.has_task_access(r_item.task_id) then
        raise exception 'no access to task item'
            using errcode = 'insufficient_privilege';
    end if;

    select * into r_task from public.tasks where id = r_item.task_id;

    if private.project_role_of(r_task.project_id) = 'viewer' then
        raise exception 'viewers cannot modify items'
            using errcode = 'insufficient_privilege';
    end if;
    if r_task.status = 'archived' or not private.project_is_active(r_task.project_id) then
        raise exception 'task is archived';
    end if;
    if r_item.is_archived then
        raise exception 'task item is archived';
    end if;

    -- idempotent no-op: repeated identical state produces no history events
    if r_item.is_completed = p_completed then
        return p_completed;
    end if;

    update public.task_items
    set is_completed = p_completed
    where id = r_item.id;

    v_action := case when p_completed then 'checked' else 'unchecked' end;
    v_audit_action := v_action::text::public.audit_action;

    insert into public.item_actions
        (project_id, task_id, task_item_id, user_id, action)
    values
        (r_task.project_id, r_task.id, r_item.id, v_user, v_action);

    insert into public.audit_log
        (project_id, user_id, action, entity_type, entity_id, old_data, new_data)
    values
        (r_task.project_id, v_user, v_audit_action, 'task_item', r_item.id,
         jsonb_build_object('is_completed', r_item.is_completed),
         jsonb_build_object('is_completed', p_completed));

    return p_completed;
end
$$;

-- Approve task access. owner/admin only; target must be a project member.
create function public.approve_task_member(p_task_id uuid, p_user_id uuid)
returns void
language plpgsql
security definer
set search_path = private, public
as $$
declare
    v_user uuid := private.require_auth();
    v_project_id uuid := private.task_project_id(p_task_id);
begin
    if not private.is_project_admin(v_project_id) then
        raise exception 'only owner/admin can approve task members'
            using errcode = 'insufficient_privilege';
    end if;
    if not private.project_is_active(v_project_id) then
        raise exception 'project is archived';
    end if;
    if exists (select 1 from public.tasks where id = p_task_id and status = 'archived') then
        raise exception 'task is archived';
    end if;
    if not private.is_project_member(v_project_id, p_user_id) then
        raise exception 'cannot grant task access to a non project member';
    end if;
    if exists (select 1 from public.task_members
               where task_id = p_task_id and user_id = p_user_id) then
        return; -- idempotent no-op
    end if;

    insert into public.task_members (task_id, user_id, approved_by)
    values (p_task_id, p_user_id, v_user);

    insert into public.audit_log (project_id, user_id, action, entity_type, entity_id, new_data)
    values (v_project_id, v_user, 'access_approved', 'task_member', p_user_id,
            jsonb_build_object('task_id', p_task_id, 'user_id', p_user_id));
end
$$;

-- Revoke task access. Atomic: task_members row AND all task_assignees rows of
-- that user for this task are removed in the same transaction.
create function public.revoke_task_member(p_task_id uuid, p_user_id uuid)
returns void
language plpgsql
security definer
set search_path = private, public
as $$
declare
    v_user uuid := private.require_auth();
    v_project_id uuid := private.task_project_id(p_task_id);
    v_was_assignee boolean;
begin
    if not private.is_project_admin(v_project_id) then
        raise exception 'only owner/admin can revoke task members'
            using errcode = 'insufficient_privilege';
    end if;
    if not private.project_is_active(v_project_id) then
        raise exception 'project is archived';
    end if;
    if not exists (select 1 from public.task_members
                   where task_id = p_task_id and user_id = p_user_id) then
        return; -- idempotent no-op
    end if;

    select exists (
        select 1 from public.task_assignees
        where task_id = p_task_id and user_id = p_user_id
    ) into v_was_assignee;

    delete from public.task_assignees
    where task_id = p_task_id and user_id = p_user_id;

    delete from public.task_members
    where task_id = p_task_id and user_id = p_user_id;

    if v_was_assignee then
        insert into public.audit_log (project_id, user_id, action, entity_type, entity_id, new_data)
        values (v_project_id, v_user, 'assignee_removed', 'task_assignee', p_user_id,
                jsonb_build_object('task_id', p_task_id, 'user_id', p_user_id,
                                   'reason', 'task access revoked'));
    end if;

    insert into public.audit_log (project_id, user_id, action, entity_type, entity_id, new_data)
    values (v_project_id, v_user, 'access_revoked', 'task_member', p_user_id,
            jsonb_build_object('task_id', p_task_id, 'user_id', p_user_id));
end
$$;

-- Assignee must be project_member AND task_member. owner/admin only.
create function public.add_task_assignee(p_task_id uuid, p_user_id uuid)
returns void
language plpgsql
security definer
set search_path = private, public
as $$
declare
    v_user uuid := private.require_auth();
    v_project_id uuid := private.task_project_id(p_task_id);
begin
    if not private.is_project_admin(v_project_id) then
        raise exception 'only owner/admin can manage assignees'
            using errcode = 'insufficient_privilege';
    end if;
    if not private.task_is_editable(p_task_id) then
        raise exception 'task is archived';
    end if;
    if not private.is_project_member(v_project_id, p_user_id) then
        raise exception 'assignee must be a project member';
    end if;
    if not exists (select 1 from public.task_members
                   where task_id = p_task_id and user_id = p_user_id) then
        raise exception 'assignee must have access to the task (task_members)';
    end if;
    if exists (select 1 from public.task_assignees
               where task_id = p_task_id and user_id = p_user_id) then
        return; -- idempotent no-op
    end if;

    insert into public.task_assignees (task_id, user_id, assigned_by)
    values (p_task_id, p_user_id, v_user);

    insert into public.audit_log (project_id, user_id, action, entity_type, entity_id, new_data)
    values (v_project_id, v_user, 'assignee_added', 'task_assignee', p_user_id,
            jsonb_build_object('task_id', p_task_id, 'user_id', p_user_id));
end
$$;

create function public.remove_task_assignee(p_task_id uuid, p_user_id uuid)
returns void
language plpgsql
security definer
set search_path = private, public
as $$
declare
    v_user uuid := private.require_auth();
    v_project_id uuid := private.task_project_id(p_task_id);
begin
    if not private.is_project_admin(v_project_id) then
        raise exception 'only owner/admin can manage assignees'
            using errcode = 'insufficient_privilege';
    end if;
    if not private.project_is_active(v_project_id) then
        raise exception 'project is archived';
    end if;
    if not exists (select 1 from public.task_assignees
                   where task_id = p_task_id and user_id = p_user_id) then
        return; -- idempotent no-op
    end if;

    delete from public.task_assignees
    where task_id = p_task_id and user_id = p_user_id;

    insert into public.audit_log (project_id, user_id, action, entity_type, entity_id, new_data)
    values (v_project_id, v_user, 'assignee_removed', 'task_assignee', p_user_id,
            jsonb_build_object('task_id', p_task_id, 'user_id', p_user_id));
end
$$;

-- Add a project member (owner/admin only; role 'owner' reserved for transfer).
create function public.add_project_member(p_project_id uuid, p_user_id uuid, p_role public.project_role)
returns void
language plpgsql
security definer
set search_path = private, public
as $$
declare
    v_user uuid := private.require_auth();
begin
    if not private.is_project_admin(p_project_id) then
        raise exception 'only owner/admin can manage project members'
            using errcode = 'insufficient_privilege';
    end if;
    if not private.project_is_active(p_project_id) then
        raise exception 'project is archived';
    end if;
    if p_role = 'owner' then
        raise exception 'use transfer_project_ownership to set a new owner';
    end if;
    if exists (select 1 from public.project_members
               where project_id = p_project_id and user_id = p_user_id) then
        raise exception 'user is already a project member';
    end if;

    insert into public.project_members (project_id, user_id, role)
    values (p_project_id, p_user_id, p_role);

    insert into public.audit_log (project_id, user_id, action, entity_type, entity_id, new_data)
    values (p_project_id, v_user, 'member_added', 'project_member', p_user_id,
            jsonb_build_object('user_id', p_user_id, 'role', p_role));
end
$$;

-- Remove a project member (owner/admin only). Removing the owner is forbidden
-- — transfer ownership first. The removed user also loses access to all tasks
-- of the project (task_members + task_assignees are cleaned up atomically).
create function public.remove_project_member(p_project_id uuid, p_user_id uuid)
returns void
language plpgsql
security definer
set search_path = private, public
as $$
declare
    v_user uuid := private.require_auth();
    v_role public.project_role;
begin
    if not private.is_project_admin(p_project_id) then
        raise exception 'only owner/admin can manage project members'
            using errcode = 'insufficient_privilege';
    end if;
    if not private.project_is_active(p_project_id) then
        raise exception 'project is archived';
    end if;

    select role into v_role
    from public.project_members
    where project_id = p_project_id and user_id = p_user_id;

    if not found then
        return; -- idempotent no-op
    end if;
    if v_role = 'owner' then
        raise exception 'cannot remove the project owner — transfer ownership first';
    end if;

    delete from public.task_assignees a
    using public.tasks t
    where a.task_id = t.id
      and t.project_id = p_project_id
      and a.user_id = p_user_id;

    delete from public.task_members m
    using public.tasks t
    where m.task_id = t.id
      and t.project_id = p_project_id
      and m.user_id = p_user_id;

    delete from public.project_members
    where project_id = p_project_id and user_id = p_user_id;

    insert into public.audit_log (project_id, user_id, action, entity_type, entity_id, old_data)
    values (p_project_id, v_user, 'member_removed', 'project_member', p_user_id,
            jsonb_build_object('user_id', p_user_id, 'role', v_role));
end
$$;

-- Change a member role.
--  * owner may change roles of admin/member/viewer;
--  * admin may change roles of member/viewer only (including self-demotion),
--    never of another admin and never of the owner;
--  * the 'owner' role itself can only change via transfer_project_ownership.
create function public.change_member_role(p_project_id uuid, p_user_id uuid, p_new_role public.project_role)
returns void
language plpgsql
security definer
set search_path = private, public
as $$
declare
    v_user        uuid := private.require_auth();
    v_caller_role public.project_role := private.project_role_of(p_project_id);
    v_target_role public.project_role := private.project_role_of(p_project_id, p_user_id);
begin
    if v_caller_role not in ('owner', 'admin') then
        raise exception 'only owner/admin can change roles'
            using errcode = 'insufficient_privilege';
    end if;
    if v_target_role is null then
        raise exception 'target user is not a project member';
    end if;
    if v_target_role = 'owner' then
        raise exception 'the owner role can only be changed via transfer_project_ownership';
    end if;
    if p_new_role = 'owner' then
        raise exception 'use transfer_project_ownership to set a new owner';
    end if;
    if v_caller_role = 'admin' and v_target_role = 'admin' and p_user_id <> v_user then
        raise exception 'admin cannot change the role of another admin'
            using errcode = 'insufficient_privilege';
    end if;
    if not private.project_is_active(p_project_id) then
        raise exception 'project is archived';
    end if;

    update public.project_members
    set role = p_new_role
    where project_id = p_project_id and user_id = p_user_id;

    insert into public.audit_log (project_id, user_id, action, entity_type, entity_id, old_data, new_data)
    values (p_project_id, v_user, 'role_changed', 'project_member', p_user_id,
            jsonb_build_object('user_id', p_user_id, 'role', v_target_role),
            jsonb_build_object('user_id', p_user_id, 'role', p_new_role));
end
$$;

-- Atomic ownership transfer: old owner -> admin, new owner -> owner.
-- Only the current owner may call this.
create function public.transfer_project_ownership(p_project_id uuid, p_new_owner_id uuid)
returns void
language plpgsql
security definer
set search_path = private, public
as $$
declare
    v_user     uuid := private.require_auth();
    v_new_role public.project_role := private.project_role_of(p_project_id, p_new_owner_id);
begin
    if not private.is_project_owner(p_project_id) then
        raise exception 'only the current owner can transfer ownership'
            using errcode = 'insufficient_privilege';
    end if;
    if p_new_owner_id = v_user then
        raise exception 'cannot transfer ownership to yourself';
    end if;
    if v_new_role is null then
        raise exception 'new owner must be a project member';
    end if;
    if not private.project_is_active(p_project_id) then
        raise exception 'project is archived';
    end if;

    update public.project_members set role = 'admin'
    where project_id = p_project_id and user_id = v_user;

    update public.project_members set role = 'owner'
    where project_id = p_project_id and user_id = p_new_owner_id;

    insert into public.audit_log (project_id, user_id, action, entity_type, entity_id, old_data, new_data)
    values (p_project_id, v_user, 'role_changed', 'project_member', v_user,
            jsonb_build_object('user_id', v_user, 'role', 'owner'),
            jsonb_build_object('user_id', v_user, 'role', 'admin')),
           (p_project_id, v_user, 'role_changed', 'project_member', p_new_owner_id,
            jsonb_build_object('user_id', p_new_owner_id, 'role', v_new_role),
            jsonb_build_object('user_id', p_new_owner_id, 'role', 'owner'));
end
$$;

-- Archive a project (owner/admin). Read-only afterwards for everyone via RLS;
-- history is preserved. 'archived' audit entry is written by the
-- trg_projects_audit trigger.
create function public.archive_project(p_project_id uuid)
returns void
language plpgsql
security definer
set search_path = private, public
as $$
declare
    v_user uuid := private.require_auth();
begin
    if not private.is_project_admin(p_project_id) then
        raise exception 'only owner/admin can archive the project'
            using errcode = 'insufficient_privilege';
    end if;

    update public.projects
    set status = 'archived', archived_at = now()
    where id = p_project_id and status = 'active';
end
$$;

-- Archive a task (owner/admin). 'archived' audit entry is written by the
-- trg_tasks_audit trigger.
create function public.archive_task(p_task_id uuid)
returns void
language plpgsql
security definer
set search_path = private, public
as $$
declare
    v_user uuid := private.require_auth();
    v_project_id uuid := private.task_project_id(p_task_id);
begin
    if not private.is_project_admin(v_project_id) then
        raise exception 'only owner/admin can archive tasks'
            using errcode = 'insufficient_privilege';
    end if;
    if not private.project_is_active(v_project_id) then
        raise exception 'project is archived';
    end if;

    update public.tasks
    set status = 'archived', archived_at = now()
    where id = p_task_id and status <> 'archived';
end
$$;

-- Archive a task item (owner/admin). History is preserved.
create function public.archive_task_item(p_task_item_id uuid)
returns void
language plpgsql
security definer
set search_path = private, public
as $$
declare
    v_user uuid := private.require_auth();
    r public.task_items%rowtype;
begin
    select * into r from public.task_items where id = p_task_item_id;

    if not found then
        raise exception 'task item not found';
    end if;
    if not private.is_project_admin(private.task_project_id(r.task_id)) then
        raise exception 'only owner/admin can archive task items'
            using errcode = 'insufficient_privilege';
    end if;
    if not private.task_is_editable(r.task_id) then
        raise exception 'task is archived';
    end if;
    if r.is_archived then
        return; -- idempotent no-op
    end if;

    update public.task_items
    set is_archived = true, archived_at = now()
    where id = r.id;

    insert into public.audit_log (project_id, user_id, action, entity_type, entity_id, old_data, new_data)
    select t.project_id, v_user, 'archived', 'task_item', r.id,
           jsonb_build_object('is_archived', false),
           jsonb_build_object('is_archived', true)
    from public.tasks t where t.id = r.task_id;
end
$$;

-- -----------------------------------------------------------------------------
-- RPC grants: callable by authenticated (and service_role); never by anon.
-- -----------------------------------------------------------------------------

do $$
begin
    execute 'revoke all on all functions in schema public from public, anon';

    execute 'grant execute on function
        public.create_project(text, text),
        public.create_task(uuid, text, text),
        public.create_task_item(uuid, text, text, numeric),
        public.update_task_item(uuid, text, text, numeric),
        public.set_task_item_state(uuid, boolean),
        public.approve_task_member(uuid, uuid),
        public.revoke_task_member(uuid, uuid),
        public.add_task_assignee(uuid, uuid),
        public.remove_task_assignee(uuid, uuid),
        public.add_project_member(uuid, uuid, public.project_role),
        public.remove_project_member(uuid, uuid),
        public.change_member_role(uuid, uuid, public.project_role),
        public.transfer_project_ownership(uuid, uuid),
        public.archive_project(uuid),
        public.archive_task(uuid),
        public.archive_task_item(uuid)
        to authenticated, service_role';
end
$$;

-- NOTE on Realtime: no sync/business logic is embedded in triggers; the schema
-- does not obstruct a future Supabase Realtime subscription (tables are plain,
-- timestamps are timestamptz, history is append-only).