import { ActivityIndicator, StyleSheet, TouchableOpacity, type TouchableOpacityProps } from 'react-native';
import { ThemedText } from '@/components/ui/text';
import { colors, radii } from '@/components/ui/theme';
type ButtonProps = { variant?: 'primary' | 'secondary' | 'outline' | 'ghost' | 'destructive'; size?: 'sm' | 'md' | 'lg'; disabled?: boolean; loading?: boolean; fullWidth?: boolean; onPress?: () => void; children: React.ReactNode } & Omit<TouchableOpacityProps, 'onPress' | 'disabled'>;
export function Button({ variant = 'primary', size = 'md', disabled = false, loading = false, fullWidth = false, onPress, children, style, ...rest }: ButtonProps) {
  const unavailable = disabled || loading;
  return <TouchableOpacity onPress={unavailable ? undefined : onPress} disabled={unavailable} activeOpacity={0.72} accessibilityRole="button" accessibilityState={{ disabled: unavailable, busy: loading }} style={[styles.container, styles[variant], sizes[size], fullWidth && styles.fullWidth, unavailable && styles.disabled, style]} {...rest}>{loading ? <ActivityIndicator size="small" color={variant === 'primary' || variant === 'destructive' ? colors.surface : colors.text} /> : <ThemedText type="small" style={[styles.text, (variant === 'secondary' || variant === 'outline') && styles.darkText, variant === 'ghost' && styles.ghostText]}>{children}</ThemedText>}</TouchableOpacity>;
}
const sizes = { sm: { minHeight: 44, paddingHorizontal: 12 }, md: { minHeight: 48, paddingHorizontal: 16 }, lg: { minHeight: 52, paddingHorizontal: 20 } };
const styles = StyleSheet.create({ container: { justifyContent: 'center', alignItems: 'center', borderRadius: radii.md, flexDirection: 'row', gap: 8 }, primary: { backgroundColor: colors.primary }, secondary: { backgroundColor: colors.surfaceMuted, borderColor: colors.border, borderWidth: 1 }, outline: { backgroundColor: 'transparent', borderColor: colors.borderStrong, borderWidth: 1 }, ghost: { backgroundColor: 'transparent' }, destructive: { backgroundColor: colors.destructive }, text: { color: colors.surface, fontWeight: '700' }, darkText: { color: colors.text }, ghostText: { color: colors.primary }, disabled: { opacity: 0.5 }, fullWidth: { width: '100%' } });
